### ISSUE TITLE
Dont work for me

### ISSUE THREAD

**Issue by MarceloTDF** [eight04/image-picka#29] opened 2017-12-10 12:29 UTC
I has installed this add ons but save files to folder *.jpg, but i cant open ... 

win 10 64 firefox 58

i download images thechive.com

**Comment by eight04** [comment] 2017-12-10 15:30
I tested on this page: http://thechive.com/2017/12/10/the-best-tourist-destinations-to-visit-before-they-get-too-popular-21-photos/

![image](https://user-images.githubusercontent.com/1324510/33806350-e030aec2-de01-11e7-8a3c-39421fa03593.png)

> save files to folder *.jpg, but i cant open

Did you mean that images are successfully downloaded but they can't be opened by your image viewer?

**Comment by MarceloTDF** [comment] 2017-12-10 17:13
![nopick](https://user-images.githubusercontent.com/30437891/33807353-35de70a0-ddb4-11e7-8bc3-45e41088deb6.gif)

**Comment by MarceloTDF** [comment] 2017-12-10 17:17
![nopick](https://user-images.githubusercontent.com/30437891/33807382-df5c21ae-ddb4-11e7-87af-e5811442e20c.gif)

the image more big

**Comment by eight04** [comment] 2017-12-10 17:45
Since images are successfully downloaded and could be previewed in explorer, I think the problem is your image viewer. Maybe the image viewer can't handle unicode character `：` in the folder name. You can try to remove that character and see if it fixes the problem.

I'm going to close the issue since it is not related to Image Picka.

BTW, I use [Honeyview](http://www.bandisoft.com/honeyview/) as my image viewer.

**Closed by eight04** 2017-12-10 17:45 UTC
