### ISSUE TITLE
Version 0.9.1 seems buggy

### ISSUE THREAD

**Issue by DenB10** [eight04/image-picka#138] opened 2018-10-24 21:25 UTC
Hi,
I think I've noticed some bugs (?) in the last version:
1) Batch download: Image Picka returns "An unexpected error occurred" with option "Collect images from frames recursively" enabled.
2) Batch download : Image Picka asks where to save each file if the option "Ask me where to save the image..." is enabled under "Download Single Image".
3) Not a bug but rather an unnecessary option "Close tabs after saving" since the same option exists in the batch download UI.
I don't know in what this version is better then the 0.8.6 which works like a charm by me.
Note I'm using FF 60 esr.
Regards,
DenB

**Comment by eight04** [comment] 2018-10-25 10:58
> Batch download: Image Picka returns "An unexpected error occurred" with option "Collect images from frames recursively" enabled.

I can't reproduce it on 60.3.0esr. Could you post the URL causing the error?

> Image Picka asks where to save each file if the option "Ask me where to save the image..." is enabled under "Download Single Image".

https://github.com/eight04/image-picka/issues/139

> 3\. Not a bug but rather an unnecessary option "Close tabs after saving" since the same option exists in the batch download UI.

I decided to put some batch options also in the options page so you can change the settings without opening the batch download UI. See also https://github.com/eight04/image-picka/issues/130.

**Comment by DenB10** [comment] 2018-10-25 14:50
>

**Comment by DenB10** [comment] 2018-10-25 14:56
Point 2 : fixed with version 0.9.2, sorry because I haven't read the other posts!
Point 1 : solved with previous patch, I don't know why? In fact, the issue occurred with all URLs!
Point 3 : OK, that's your choice!
Thanks for your work!

**Comment by DenB10** [comment] 2018-10-25 18:08
Point 1 : I've solved the problem!
I've always used Image Picka through the web page context menu items without any problem before (until version 0.8.6).
I had the good idea of using once the toolbar button and there, I've noticed that Image Picka requested access permission to the browser activity for browsing. After acceptation, no more error message and that's OK now.
Maybe adding this permission in the manifest???

**Comment by eight04** [comment] 2018-10-26 02:36
I can reproduce it with 60.3.0esr + context menu click.

I know that requesting permissions while clicking context menu may throw an error in older versions of Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1454627. (I thought they have fixed this bug in Firefox 60 ESR)

Maybe we should document this in README.

----

> Maybe adding this permission in the manifest?

Currently, `webNavigation` permission is marked as `optional` in the manifest. It is only required when needed i.e. `Collect images from frames recursively` is used.

**Comment by DenB10** [comment] 2018-10-26 08:12
OK, I've seen the `webNavigation` permission entry in the manifest.

I'm using FF 60.3.0esr too but the permission request didn't occur on IP 0.8.6!
I made tests on a fresh installed profile. 
So I've concluded the problem doesn't come from my FF installation but from IP 0.9.2 itself, am I right?

Note: it isn't a big problem but document it in README seems a good idea.

**Comment by eight04** [comment] 2018-10-26 08:42
> So I've concluded the problem doesn't come from my FF installation but from IP 0.9.2 itself, am I right?

Fifty-fifty. The permission problem does exist in 0.8.6, but you would rarely hit it because of an `executeScript` workaround ([the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1454627) is not fixed yet at the moment). See https://github.com/eight04/image-picka/pull/76#issuecomment-386516110.

In 0.9.0, I simplified the code and dropped the `executeScript` workaround. Now the extension just requests `webNavigation` permission when needed.

**Comment by DenB10** [comment] 2018-10-26 08:51
OK, thanks for your well documented explanations!

**Comment by eight04** [comment] 2018-10-26 14:38
Documented in v0.9.3.

**Closed by eight04** 2018-10-26 14:38 UTC
